# Generated by Django 3.2.5 on 2021-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fleet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
